### ISSUE TITLE
mstring matcher needs tiny change

### ISSUE THREAD

**Issue by dfkaye** [rjrodger/mstring#1]
This line needs a slight update:

```
var m  = fs.match(/^function\s*\(\)\s*\{\s*\/\*\*\*\n([\s\S]*)\n\*\*\*\/\s*\}$/) 
```

\n needs \* - \n([\s\S]_)\n => \n_([\s\S]_)\n_:

```
var m  = fs.match(/^function\s*\(\)\s*\{\s*\/\*\*\*\n*([\s\S]*)\n*\*\*\*\/\s*\}$/) 
```

I can send a pull request if you want but it's a very tiny copy+paste change.

**Comment by rjrodger** [comment]
Thank You!
oh, pull request please :)
Add your self to the contributors list in package.json too
